In [1]:
import numpy as np

# 축 사용하기 

## 축 늘리기

In [2]:
x = np.arange(6,10)
x

array([6, 7, 8, 9])

In [3]:
x.shape

(4,)

In [4]:
y = x[:, np.newaxis]
y

array([[6],
       [7],
       [8],
       [9]])

In [5]:
y.shape

(4, 1)

In [6]:
z = x[np.newaxis, :]
z

array([[6, 7, 8, 9]])

In [7]:
z.shape

(1, 4)

## 축별 합산

In [8]:
x = np.arange(1,9).reshape(2,2,2)
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
np.sum(x)

36

In [10]:
np.sum(x, axis=0)

array([[ 6,  8],
       [10, 12]])

In [11]:
np.sum(x, axis=1)

array([[ 4,  6],
       [12, 14]])

In [12]:
np.sum(x, axis=2)

array([[ 3,  7],
       [11, 15]])

## 축 변환 

* transpose
* moveaxis
  * Move axes of an array to new positions.
  * Other axes remain in their original order.
* swapaxis

In [29]:
x = np.zeros([3,4,5,6])
x.shape

(3, 4, 5, 6)

In [30]:
np.transpose(x).shape

(6, 5, 4, 3)

In [31]:
np.moveaxis(x, 0, 2).shape    

(4, 5, 3, 6)

In [32]:
np.moveaxis(x, 0, -1).shape    

(4, 5, 6, 3)

In [33]:
np.moveaxis(x, -1, 0).shape    

(6, 3, 4, 5)

In [34]:
np.swapaxes(x, 0, 2).shape

(5, 4, 3, 6)

## 축 확장 

In [35]:
x = np.zeros([2])
x.shape

(2,)

In [36]:
np.expand_dims(x, axis=1).shape

(2, 1)

In [37]:
np.expand_dims(x, axis=0).shape

(1, 2)

## 축 축소

In [39]:
x = np.zeros([2,2])
x.shape

(2, 2)

In [46]:
x.flatten().shape

(4,)

In [47]:
x.ravel().shape

(4,)

In [44]:
np.may_share_memory(x.flatten(), x)

False

In [45]:
np.may_share_memory(x.ravel(), x)

True