In [1]:
import numpy as np

# Contents

* 소수점 처리 
  * fix, trunc, ceil, floor, round, around
* 몫, 나머지 
  * remainder, divmod
* 논리연산
* 비교연산
* 셋트연산

## 소수점 처리

* fix, trunc, ceil, floor, round, around

In [15]:
x = np.array([3.14, 4.72])
x

array([3.14, 4.72])

In [16]:
np.fix(x) # 내림

array([3., 4.])

In [17]:
assert np.array_equal(np.fix(x), np.trunc(x))   # np.trunc와 동일
assert np.array_equal(np.fix(x), np.floor(x))   # np.floor와 동일

In [19]:
np.ceil(x) # 올림 

array([4., 5.])

In [21]:
np.round(x)  # 반올림

array([3., 5.])

In [23]:
np.round(x, 1)  # 반올림하도 소숫점 첫째 자리 기준

array([3.1, 4.7])

## 나누기, 몫, 나머지

In [24]:
x = np.array([2,4,5])
x

array([2, 4, 5])

In [25]:
x / x 

array([1., 1., 1.])

In [26]:
x // x # 몫만

array([1, 1, 1])

In [28]:
assert np.array_equal( x//x, np.floor_divide(x,x))  # np.floor_divide와 동일

In [36]:
np.remainder(5,3) # 나머지만

assert np.remainder(5,3) == 5 % 3

In [37]:
 np.divmod(5,3)  # 몫과 나머지

(1, 2)

## 논리연산 

In [39]:
x = np.array([1,0,0], dtype=bool)
y = np.array([1,1,0], dtype=bool)

In [40]:
np.logical_and(x,y)

array([ True, False, False])

In [44]:
x & x

array([ True, False, False])

In [47]:
np.logical_or(x,y)

array([ True,  True, False])

In [50]:
x | y

array([ True,  True, False])

In [51]:
np.logical_xor(x,y)

array([False,  True, False])

In [52]:
x ^ y

array([False,  True, False])

In [43]:
np.logical_not(x)

array([False,  True,  True])

In [53]:
~x

array([False,  True,  True])

## 비교연산

In [55]:
x = np.array([1,2,3])
y = np.array([2,3,1])

In [58]:
np.less(x,y)

array([ True,  True, False])

In [57]:
x < y

array([ True,  True, False])

In [59]:
np.greater_equal(x,y)

array([False, False,  True])

In [60]:
x >= y

array([False, False,  True])

## 셋트연산

In [72]:
x = np.array([[1,2,3],[4,5,6], [3,4,5]])
y = np.array([[11,21,13],[4,15,6], [3,14,5]])

In [73]:
# 합집합 1d
np.union1d(x,y)

array([ 1,  2,  3,  4,  5,  6, 11, 13, 14, 15, 21])

In [74]:
# 교집합 1d
np.intersect1d(x,y)

array([3, 4, 5, 6])

In [75]:
np.setdiff1d(x,y)  # X - Y 

array([1, 2])

In [76]:
np.setdiff1d(y,x)  # Y - X

array([11, 13, 14, 15, 21])

In [77]:
np.setxor1d(x,y) # X union Y - X intersect Y

array([ 1,  2, 11, 13, 14, 15, 21])