In [1]:
import numpy as np

# Contents

* 백터 내적/외적

## 벡터 내적 

In [6]:
x = np.array([3,4])
y = np.array([5,6])

In [7]:
x * y  # element-wise product

array([15, 24])

In [8]:
x @ y # 내적

39

In [13]:
assert np.array_equal(x @ y, np.dot(x,y)) == True
assert np.array_equal(x @ y, np.inner(x,y)) == True

## 벡터 외적

In [36]:
x = np.array([3,4])
y = np.array([5,6])

np.cross(x,y)

array(-2)

In [15]:
x = np.array([3,4,5])
y = np.array([5,6,7])

np.cross(x,y)

array([-2,  4, -2])

## 행렬곱 (dot product)

* @
* np.dot
* np.matmul

In [19]:
x = np.array([[1,2],[3,4]])
y = np.array([[4,5],[6,7]])

x @ y

array([[16, 19],
       [36, 43]])

In [21]:
assert np.array_equal(x @ y, np.dot(x,y)) == True
assert np.array_equal(x @ y, np.matmul(x,y)) == True

In [24]:
try: 
    np.matmul(x,2)   # 오직 행렬만 취급
except Exception as e:
    print(e)

matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)


In [25]:
np.dot(x,2)

array([[2, 4],
       [6, 8]])

## 행렬을 벡터로 dot 연산 : vdot

In [26]:
x = np.array([[1,2],[3,4]])
y = np.array([[4,5],[6,7]])

np.vdot(x,y)

60

In [30]:
x.flatten() @ y.flatten()   # 각 행렬을 flat 한 다음 내적 

60

## 행렬 Inner 연산

* dot 연산과 동일
* AB 이면 B를 열벡터로 분해후, 각각 dot product 후, concat한 것

In [32]:
x = np.array([[1,2],[3,4]])
y = np.array([[4,5],[6,7]])

np.inner(x, y)

array([[14, 20],
       [32, 46]])

In [34]:
np.dot(x, y[0]).reshape(2,1)

array([[14],
       [32]])

In [35]:
np.dot(x, y[1]).reshape(2,1)

array([[20],
       [46]])

## 행렬 outer 연산

* 두 행렬을 벡터로 만들고, 이 벡터들을 브로드캐스팅한 배열을 만든후 element-wise product한 결과

In [38]:
x = np.array([[1,2],[3,4]])
y = np.array([[4,5],[6,7]])

np.outer(x,y)

array([[ 4,  5,  6,  7],
       [ 8, 10, 12, 14],
       [12, 15, 18, 21],
       [16, 20, 24, 28]])

In [41]:
a = x.flatten().reshape(4,1)
a

array([[1],
       [2],
       [3],
       [4]])

In [42]:
b = y.flatten().reshape(1,4)
b

array([[4, 5, 6, 7]])

In [47]:
broadcasted = np.broadcast_arrays(a,b)
broadcasted

[array([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4]]),
 array([[4, 5, 6, 7],
        [4, 5, 6, 7],
        [4, 5, 6, 7],
        [4, 5, 6, 7]])]

In [49]:
broadcasted[0] * broadcasted[1]

array([[ 4,  5,  6,  7],
       [ 8, 10, 12, 14],
       [12, 15, 18, 21],
       [16, 20, 24, 28]])

## 행렬의 cross 연산

* 행벡터끼리 cross 연산 한 것은 concat

In [52]:
x = np.array([[3,4],[5,6]])
y = np.array([[2,5],[7,8]])

np.cross(x,y)

array([ 7, -2])

In [53]:
np.cross(x[0], y[0])

array(7)

In [54]:
np.cross(x[1], y[1])

array(-2)