In [1]:
import numpy as np

# Contents

* axes = 0 : tensor product a X b
* axes = 1 : tensor dot product a @ b
* axes = 2 : (default) tensor double contraction a:b

# Tensor product

* expansion 
  * 2x2 X 2x2  =>  2,2,2,2

In [8]:
x = np.array([[1,0],[0,1]])
y = np.array([[4,5],[6,7]])

In [10]:
product = np.tensordot(x,y, axes=0)
product

array([[[[4, 5],
         [6, 7]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[4, 5],
         [6, 7]]]])

In [11]:
product.shape

(2, 2, 2, 2)

# Tensor double contraction

In [20]:
x = np.array([[[9,6],[5,2]],[[1,2],[2,3]]])
y = np.array([[[1,4],[3,9]],[[5,4],[1,4]]])

np.tensordot(x,y, axes=2)

array([[ 54, 118],
       [ 20,  42]])

In [21]:
# 수동으로 하기 

## 3차원을 2차원으로 contract
x_2d = x.reshape(2,4)
y_2d = y.reshape(4,2)

## dot
x_2d @ y_2d

array([[ 54, 118],
       [ 20,  42]])

# Tensor dot product

In [3]:
x = np.array([[1,2],[3,4]])
y = np.array([[4,5],[6,7]])

In [5]:
np.tensordot(x,y, axes=1)

array([[16, 19],
       [36, 43]])

In [6]:
assert np.array_equal( np.tensordot(x,y, axes=1) , np.dot(x,y) ) == True

# 크로네커 곱 

## 1차원의 경우 

In [22]:
x = np.array([1,2,3])
y = np.array([10,20,30])

np.kron(x,y)

array([10, 20, 30, 20, 40, 60, 30, 60, 90])

In [26]:
c1 = x[0] * y
c1

array([10, 20, 30])

In [27]:
c2 = x[1] * y
c2

array([20, 40, 60])

In [28]:
c3 = x[2] * y
c3

array([30, 60, 90])

In [31]:
kron = np.hstack([c1,c2,c3])
kron 

array([10, 20, 30, 20, 40, 60, 30, 60, 90])

In [37]:
assert kron.shape[0] == x.shape[0] * y.shape[0]

## 2차원의 경우 

In [40]:
x = np.arange(1,5).reshape(2,2)
y = np.eye(2)

np.kron(x,y)

array([[1., 0., 2., 0.],
       [0., 1., 0., 2.],
       [3., 0., 4., 0.],
       [0., 3., 0., 4.]])

In [48]:
# 수동으로 만들기 

x_1 = np.repeat(x,2, axis=0)
x_1

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [50]:
x_2 = np.repeat(x_1,2, axis=1)
x_2

array([[1, 1, 2, 2],
       [1, 1, 2, 2],
       [3, 3, 4, 4],
       [3, 3, 4, 4]])

In [51]:
y_ = np.tile(y, (2,2))
y_

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [53]:
x_2 * y_

array([[1., 0., 2., 0.],
       [0., 1., 0., 2.],
       [3., 0., 4., 0.],
       [0., 3., 0., 4.]])