In [1]:
import numpy as np

# Contents

* sort
* asmatrix, asarray
* fill, full
* fliplr, flipud
* rot90
* roll

## Sort

In [2]:
x = np.array([6,5,4,1,2,3])
x

array([6, 5, 4, 1, 2, 3])

In [4]:
np.sort(x)

array([1, 2, 3, 4, 5, 6])

In [5]:
sort_arg = np.argsort(x)   # 정렬된 인덱스 
sort_arg

array([3, 4, 5, 2, 1, 0])

In [7]:
x[sort_arg]  # 정렬된 인덱스로 원래 배열의 정렬

array([1, 2, 3, 4, 5, 6])

In [8]:
x = np.array([[4,3],[1,2]])
x

array([[4, 3],
       [1, 2]])

In [9]:
np.sort(x, axis=0)  # 행방향 정렬 

array([[1, 2],
       [4, 3]])

In [10]:
np.sort(x, axis=1)  # 열방향 정렬 

array([[3, 4],
       [1, 2]])

In [11]:
np.sort(['h', 'a', 'b']) # 문자열 정렬

array(['a', 'b', 'h'], dtype='<U1')

## 배열 클래스 변환 (array <-> matrix)

In [12]:
mat = np.matrix([1,2,3,4])
type(mat)

numpy.matrix

In [14]:
type(np.asarray(mat))

numpy.ndarray

In [13]:
arr = np.array([1,2,3,4])
type(arr)

numpy.ndarray

In [16]:
matted = np.asmatrix(arr)
type(matted)

numpy.matrix

In [17]:
matted   #  1차원 array를 matrix로 바꾸면 2차원이 된다.

matrix([[1, 2, 3, 4]])

## 배열 원소의 값 변경

In [21]:
x = np.ones(4)
x

array([1., 1., 1., 1.])

In [22]:
x.fill(3)   # 내부 변수 직접 변경
x

array([3., 3., 3., 3.])

In [23]:
np.full(x.shape, 99)  # 형상 정보로 바탕으로 채우기 

array([99, 99, 99, 99])

## 위치 변경

In [24]:
x = np.arange(4).reshape(2,2)
x

array([[0, 1],
       [2, 3]])

In [25]:
np.fliplr(x)   # 열을 기준으로 좌우로 flip 한다. 

array([[1, 0],
       [3, 2]])

In [26]:
np.flipud(x)   # 행을 기준으로 위아래로 flip 한다. 

array([[2, 3],
       [0, 1]])

In [27]:
x = np.arange(8).reshape(2,2,2)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [28]:
np.fliplr(x)  # 3차원에서는 좌우는 세번째 축을 기준으로 flip

array([[[2, 3],
        [0, 1]],

       [[6, 7],
        [4, 5]]])

In [29]:
np.flipud(x)  # 3차원에서는 위아래는 두번째 축을 기준으로 flip

array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

## 회전

In [30]:
x = np.arange(4).reshape(2,2)
x

array([[0, 1],
       [2, 3]])

In [31]:
np.rot90(x) # 90도

array([[1, 3],
       [0, 2]])

In [32]:
np.rot90(x, 2) # 180도 

array([[3, 2],
       [1, 0]])

In [33]:
np.rot90(x, 3) # 270도 

array([[2, 0],
       [3, 1]])

# roll로 구르기

In [36]:
x = np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
np.roll(x, 1)   #  flatten 방향으로 rolling

array([[9, 0, 1, 2, 3],
       [4, 5, 6, 7, 8]])

In [46]:
np.roll(x, -1) #  flatten 방향으로 rolling

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [50]:
np.roll(x, -1, axis=0) # 행 방향으로 rolling

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [49]:
np.roll(x, -1, axis=1) # 열 방향으로 rolling

array([[1, 2, 3, 4, 0],
       [6, 7, 8, 9, 5]])

# 원소 점검

In [68]:
x = np.array([1+3j, 1, np.nan, np.inf, 0])
x

array([ 1.+3.j,  1.+0.j, nan+0.j, inf+0.j,  0.+0.j])

In [69]:
np.isreal(x)

array([False,  True,  True,  True,  True])

In [70]:
np.isinf(x)

array([False, False, False,  True, False])

In [71]:
np.isnan(x)

array([False, False,  True, False, False])

In [72]:
np.iscomplex(x)

array([ True, False, False, False, False])

In [73]:
np.nonzero(x)

(array([0, 1, 2, 3]),)