In [1]:
import numpy as np

# Contents

* reshape : 크기 변경만 하고 축소하거나 채워주지 않음
* resize : 축소하거나 채워줌 
* pad : 채워줌

# Reshape으로 배열의 형상 변경하기

In [6]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [5]:
x.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [8]:
x.reshape(4,-1)  # -1 로 자동 계산 

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [13]:
x.reshape(2,-1, 2).shape  # -1 로 자동 계산 

(2, 2, 2)

In [10]:
try:
    x.reshape(2,-1,-1)  # -1이 두번 들어가면 오류
except Exception as e:
    print(e)

can only specify one unknown dimension


# Resize로 크기를 늘리거나 줄이기

* np.resize 는 self-repeat
* ndarray,resize 는 zero-padding

In [14]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [17]:
np.resize(x,6)  # 자신으로 repeat, 즉 zero padding 이 아님

array([0, 1, 2, 3, 0, 1])

In [16]:
x.resize(6, refcheck=False)   # zero padding 임
x

array([0, 1, 2, 3, 0, 1, 2])

In [21]:
x.resize(6, refcheck=False)  # 주의! 원본 변경
x

array([0, 1, 2, 3, 0, 0])

In [23]:
np.resize(np.arange(6), (4,4))   # self-repeat

array([[0, 1, 2, 3],
       [4, 5, 0, 1],
       [2, 3, 4, 5],
       [0, 1, 2, 3]])

In [28]:
x = np.arange(6)
x.resize(4,4, refcheck=False) # zero padding
x

array([[0, 1, 2, 3],
       [4, 5, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# Padding

* pad_width : before_N, after_N
* constant_values    

In [30]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [33]:
np.pad(x, (2,0), "constant", constant_values=99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99,  1,  2],
       [99, 99,  3,  4]])

In [34]:
np.pad(x, (0,2), "constant", constant_values=99)

array([[ 1,  2, 99, 99],
       [ 3,  4, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

In [35]:
np.pad(x, (2,2), "constant", constant_values=99)

array([[99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99,  1,  2, 99, 99],
       [99, 99,  3,  4, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99]])

## 기존 값으로 패딩하기

In [36]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [37]:
np.pad(x, (1,0), "edge")

array([[1, 1, 2],
       [1, 1, 2],
       [3, 3, 4]])

In [38]:
np.pad(x, (0,1), "edge")

array([[1, 2, 2],
       [3, 4, 4],
       [3, 4, 4]])

In [39]:
np.pad(x, (1,1), "edge")

array([[1, 1, 2, 2],
       [1, 1, 2, 2],
       [3, 3, 4, 4],
       [3, 3, 4, 4]])

In [40]:
np.pad(x, (2,2), "edge")

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4],
       [3, 3, 3, 4, 4, 4],
       [3, 3, 3, 4, 4, 4]])

In [41]:
np.pad(x, (2,2), "maximum") # 행과 열의 최대값으로 padding

array([[4, 4, 3, 4, 4, 4],
       [4, 4, 3, 4, 4, 4],
       [2, 2, 1, 2, 2, 2],
       [4, 4, 3, 4, 4, 4],
       [4, 4, 3, 4, 4, 4],
       [4, 4, 3, 4, 4, 4]])

In [42]:
np.pad(x, (2,2), "minimum") # 행과 열의 최소값으로 padding

array([[1, 1, 1, 2, 1, 1],
       [1, 1, 1, 2, 1, 1],
       [1, 1, 1, 2, 1, 1],
       [3, 3, 3, 4, 3, 3],
       [1, 1, 1, 2, 1, 1],
       [1, 1, 1, 2, 1, 1]])

In [44]:
np.pad(x, (2,2), "mean") # 행과 열의 평균값으로 padding

array([[2, 2, 2, 3, 2, 2],
       [2, 2, 2, 3, 2, 2],
       [2, 2, 1, 2, 2, 2],
       [4, 4, 3, 4, 4, 4],
       [2, 2, 2, 3, 2, 2],
       [2, 2, 2, 3, 2, 2]])

In [46]:
np.pad(x, (2,2), "reflect") # mirror로 복사

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [48]:
np.pad(x, (2,2), "linear_ramp") # 선형적으로 증가/감소하도록 표현

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 2, 1, 0],
       [0, 1, 3, 4, 2, 0],
       [0, 0, 1, 2, 1, 0],
       [0, 0, 0, 0, 0, 0]])