In [1]:
import numpy as np

# 대각행렬

* np.diag
  * Extract a diagonal or construct a diagonal array
* np.eye  

In [3]:
np.diag(np.arange(1,4))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [4]:
np.diag(np.arange(1,4), k=1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [8]:
np.diag(np.arange(1,4), k=-1)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

In [9]:
np.diag([[1,2],[3,4]])

array([1, 4])

In [11]:
np.eye(3,3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

# 삼각행렬

* tril
* trilu

In [12]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
lower = np.tril(x)
lower

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [17]:
upper = np.triu(x)
upper

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [18]:
# 삼각행렬의 곱은 동일한 배열의 제곱을 처리하는 것과 같다. 
lower * lower 

array([[ 1,  0,  0],
       [16, 25,  0],
       [49, 64, 81]])

In [19]:
# 상삼각행렬과 하삼각행렬의 곱은 주 대각선의 곱
lower * upper

array([[ 1,  0,  0],
       [ 0, 25,  0],
       [ 0,  0, 81]])

# 대칭행렬 

In [21]:
x = np.array([[1,2,3],[2,3,5],[3,5,6]])
x

array([[1, 2, 3],
       [2, 3, 5],
       [3, 5, 6]])

In [22]:
np.array_equal(x, x.T)

True

In [24]:
np.array_equiv(x, x.T)

True

In [25]:
# 전치와 더하거나 곱해도 그대로 대칭 
added = x + x.T
print(added)

dot = np.dot(x,x.T)
print(dot)

[[ 2  4  6]
 [ 4  6 10]
 [ 6 10 12]]
[[14 23 31]
 [23 38 51]
 [31 51 70]]


# 반대칭(Skew Symmetric) 행렬

In [26]:
x = np.array([[0,2,-3],[-2,0,5],[3,-5,0]])
x

array([[ 0,  2, -3],
       [-2,  0,  5],
       [ 3, -5,  0]])

In [29]:
np.array_equal(x + x.T, np.zeros([3,3]))   # 전치와 합하면 영행렬

True

In [31]:
np.dot(x, x.T)   # 행렬곱은 대칭행렬로 변경

array([[ 13, -15, -10],
       [-15,  29,  -6],
       [-10,  -6,  34]])

# 치환행렬

In [32]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
p21 = np.array([[0,1,0],[1,0,0],[0,0,1]])   # 2행과 1행을 바꾸는 permutation matrix

In [36]:
np.dot(p21, x)    # 행 치환

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

In [37]:
np.dot(x,p21)   # 열 치환 

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

# 직교행렬

In [38]:
from scipy.stats import ortho_group

In [40]:
x = ortho_group.rvs(3)
x

array([[ 0.28540256, -0.7834541 , -0.55203719],
       [ 0.85997954, -0.04491245,  0.50834836],
       [ 0.42306095,  0.61982461, -0.66093637]])

In [43]:
np.allclose(np.dot(x, x.T), np.eye(3))  # Identity matrix가 된다.

True