In [1]:
import numpy as np

# 메소드나 함수로 검색하기

* item, itemset
* take, put
* choose

## item으로 검색, itemset으로 변경

In [2]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
x.item(8)

8

In [7]:
x.item((2,2))

8

In [8]:
x.itemset(8,20)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7, 20]])

## take으로 획득, put으로 변경

In [29]:
x = np.arange(9).reshape(3,3) * 10
x

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

In [24]:
x.take([1,8])  # list안의 elem을 position으로 해석

array([10, 80])

In [25]:
x.take([[1,8], [1,8]]) # list 안에 list들을 순차적으로 붙여서 append 

array([[10, 80],
       [10, 80]])

In [26]:
x.take([[1,8], [2,1], [2,3]]) # 

array([[10, 80],
       [20, 10],
       [20, 30]])

In [28]:
x.put([1,8], 999)
x

array([[  0, 999,  20],
       [ 30,  40,  50],
       [ 60,  70, 999]])

## 질의함수 사용하기 

In [31]:
x = np.arange(9).reshape(3,3) * 10
x

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

In [32]:
np.choose(0,x)    # 첫번째 행

array([ 0, 10, 20])

In [33]:
np.choose([0], x)  # 첫번째 행

array([ 0, 10, 20])

In [36]:
np.choose([ [0],[1],[1] ], x)  # 첫번째 행, 두번째 행, 두번째 행

array([[ 0, 10, 20],
       [30, 40, 50],
       [30, 40, 50]])

In [41]:
np.choose([0,1,1], x)   # 리스트로 주면 각 열에 대해서 주어진 인덱스를 행으로 해석해서 선택 (0,0), (1,1), (1,2)

array([ 0, 40, 50])

## where 사용

In [57]:
x = np.arange(9).reshape(3,3) * 10
x

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

In [43]:
np.where(x > 40)   # 행, 열 리스트 전달

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [47]:
x[ np.where(x>40) ]

array([50, 60, 70, 80])