In [1]:
import numpy as np

# 복사와 뷰 이해하기

* view()
* np.may_share_memory()

In [2]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [3]:
y = x  # view, data shared
y

array([[1, 2],
       [3, 4]])

In [4]:
x is y   # 동일한 객체를 바라보는지 확인

True

In [5]:
y[0] = 999
y

array([[999, 999],
       [  3,   4]])

In [6]:
x  # x도 바뀌었음 

array([[999, 999],
       [  3,   4]])

In [7]:
x.base is None

True

In [8]:
y.base is None

True

In [9]:
z = x.copy()   # 새로운 메모리로 생성
z

array([[999, 999],
       [  3,   4]])

In [10]:
z.base is None

True

In [11]:
g = x[:]
g.base

array([[999, 999],
       [  3,   4]])

In [12]:
g.base is x

True

In [13]:
np.may_share_memory(x,y)  # 명시적으로 메모리 공유 검사

True

In [14]:
np.may_share_memory(x,z)

False

In [15]:
h = x.view()   # view 함수로 직접적으로 view 생성 가능 
h.base  

array([[999, 999],
       [  3,   4]])

# 검색과 슬라이싱 

In [16]:
# python 에서의 슬라이싱 검색 

x = list(range(1,10))
index = slice(1,3)
x.__getitem__(index)

[2, 3]

In [17]:
# numpy에서의 슬라이싱 검색 

x = np.array([1,2,3,4,5])
index = slice(1,3)
x.__getitem__(index)

array([2, 3])

In [18]:
# 논리식으로 검색 

x.__getitem__(x < 3)

array([1, 2])