In [1]:
import numpy as np

# Contents

* 쌓기 
  * stack, hstack, vstack, row_stack, col_stack, r_, c_, dstack
* 분리하기
  * split, hsplit, vsplit, array_split

## Stack, VStack, row_stak

In [2]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [10]:
vstacked = np.stack([x,y], axis=0)
vstacked

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
assert np.array_equal(vstacked, np.vstack([x,y]))   # stack(, axis=0) 과 vstack의 동일성
assert np.array_equal(vstacked, np.row_stack([x,y])) # stack(, axis=0) 과 row_stack의 동일성

In [19]:
np.vstack([[vstacked,vstacked]])   # 2차원으로 인자를 주면 차원 확대 

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [21]:
np.row_stack([x,y])

array([[1, 2, 3],
       [4, 5, 6]])

## Stack, hstack, col_stak

In [23]:
hstacked = np.stack([x,y], axis=1)
hstacked

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
np.hstack([x,y])   # np.stack(.., axis=1) 과는 다르다. 

array([1, 2, 3, 4, 5, 6])

In [27]:
np.column_stack([x,y]) # stack(, axis=1) 과 col_stack의 동일성

array([[1, 4],
       [2, 5],
       [3, 6]])

## dstack

In [28]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [36]:
dstacked = np.dstack([x,x]) # 마지막 번째 축으로 확장하며 쌓기 (차원 확장)
dstacked

array([[[0, 0],
        [1, 1],
        [2, 2]],

       [[3, 3],
        [4, 4],
        [5, 5]]])

In [37]:
dstacked.shape

(2, 3, 2)

In [38]:
vstacked_expand = np.vstack([[x,x]]) # 마지막 번째 축으로 쌓기 (차원 확장)
vstacked_expand

array([[[0, 1, 2],
        [3, 4, 5]],

       [[0, 1, 2],
        [3, 4, 5]]])

In [39]:
vstacked_expand.shape

(2, 2, 3)

In [40]:
np.vstack([x,x])   # 일반적인 vstack

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

# 배열 쌓기 도우미 (r_, c_)

In [54]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [56]:
np.r_[x,y]

array([1, 2, 3, 4, 5, 6])

In [57]:
np.c_[x,y]

array([[1, 4],
       [2, 5],
       [3, 6]])

## split, vsplit, hsplit

In [43]:
x = np.arange(12).reshape(4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [45]:
np.split(x, [1,3], axis=0)   # 행 방향으로 3의 array로 쪼개기

[array([[0, 1, 2]]),
 array([[3, 4, 5],
        [6, 7, 8]]),
 array([[ 9, 10, 11]])]

In [48]:
np.split(x, [1,3], axis=1)   # 열 방향으로 3의 array로 쪼개기

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]]),
 array([], shape=(4, 0), dtype=int64)]

In [49]:
np.vsplit(x, [1,3])   # split(, axis=0)과 동일 

[array([[0, 1, 2]]),
 array([[3, 4, 5],
        [6, 7, 8]]),
 array([[ 9, 10, 11]])]

In [50]:
np.hsplit(x, [1,3])   # split(, axis=1)과 동일 

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]]),
 array([], shape=(4, 0), dtype=int64)]