In [1]:
import numpy as np

# Array Creation

In [2]:
np.array([1,2,3]) # from python-array

array([1, 2, 3])

In [6]:
np.array((1,2,3)) # from python-tuple

array([1, 2, 3])

In [18]:
# memory shared for two references   : base는 원본, data는 pointer

a = np.array([1,2,3])
b = a 
print(f'base comparision: {a.base is b.base}')
print(f'data comparision: {a.data is b.data}')

a[0] = 100
print(a)
print(b)

base comparision: True
data comparision: False
[100   2   3]
[100   2   3]


In [21]:
c = np.array(a)  # 공유하지 않고 새로 생성
c[0] = 99
print(c) # 새 객체 c 만 변경  
print(a)

[99  2  3]
[100   2   3]


# Array 크기/형태 조사

In [26]:
x = np.array([[1,2,3],[4,5,6]], dtype='int32')
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [27]:
x.shape

(2, 3)

In [28]:
x.ndim

2

In [29]:
x.dtype

dtype('int32')

In [37]:
x.itemsize  # int32 = 4byte

4

In [35]:
x.size
assert x.size == x.shape[0] * x.shape[1]

In [38]:
x.strides #  첫번째는 하나의 행의 byte수 = 3 * 4 = 12byte,   행이 늘어나면 12 byte만큼 늘어난다는 의미에서 strides

(12, 4)

# Flatten과 Ravel 의 차이

* flatten은 복사해서 새로 생성
* ravel은 view

In [46]:
x = np.array([[1,2,3],[4,5,6]], dtype='int32')
flatten = x.flatten()
flatten[0] = 100
print(flatten)
print(x)

[100   2   3   4   5   6]
[[1 2 3]
 [4 5 6]]


In [45]:
ravel = x.ravel()
ravel[0] = 100
print(ravel)
print(x)

[100   2   3   4   5   6]
[[100   2   3]
 [  4   5   6]]


# 3차원 배열 처리

In [58]:
x = np.array([ [[1,2,3,],[4,5,6,]], [[1,2,3,],[4,5,6,]] ], dtype='int32')
x

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)

In [59]:
x.ndim

3

In [60]:
x.shape 

(2, 2, 3)

In [61]:
x[0]

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [62]:
x[0].shape

(2, 3)

In [63]:
x.__array_interface__

{'data': (94711602043472, False),
 'strides': None,
 'descr': [('', '<i4')],
 'typestr': '<i4',
 'shape': (2, 2, 3),
 'version': 3}

In [64]:
x.strides    # 두번째 dim의 한 행의 byte수 = 3개*4byte = 12 byte
             # 첫번째 dim의 한 행의 byte수 = 6개*4byte = 24 byte

(24, 12, 4)

In [68]:
len(x.data.tobytes())  # 6 * 2 * 4 = 48 bytes

48

In [72]:
x.tolist()

[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]

In [73]:
x.data.tolist()

[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]

# hex() 로 표현

In [78]:
x = np.array([1,2,3], dtype='int32')
x

array([1, 2, 3], dtype=int32)

In [81]:
x.data.hex()   # hex string    00 00 00 01    00 00 00 02    00 00 00 03

'010000000200000003000000'

# flat 으로 iteration

In [83]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [84]:
type(x.flat)

numpy.flatiter

In [85]:
for i in x.flat:
    print(i)

0
1
2
3
4
5


In [89]:
x.flat[2:5]    # flatten해서 1dim 상황에서 from:to

array([2, 3, 4])

# tobyte로 바이트 전환, frombuffer로 바이트에서 로딩

* view이다. 
* OWNDATA=FALSE

In [111]:
x = np.array([1,2,3], dtype='int32')
buffer = x.tobytes()
buffer

b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'

In [112]:
y = np.frombuffer(x, dtype=np.int32, offset=0, count=-1)
y

array([1, 2, 3], dtype=int32)

In [114]:
y.flags  # OWNDATA : False

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [115]:
x.flags # OWNDATA : True

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

# ndarray와 matrix 비교

In [117]:
* ndarray에서 *는 element-wise multiply, matrix에서는 

SyntaxError: invalid syntax (<ipython-input-117-32b393dc5236>, line 1)

In [118]:
# super class 

print(f'ndarray base class: {np.ndarray.__bases__}')
print(f'matrix base class: {np.matrix.__bases__}')

ndarray base class: (<class 'object'>,)
matrix base class: (<class 'numpy.ndarray'>,)


In [135]:
mat = np.matrix([1,2,3,4])
mat

matrix([[1, 2, 3, 4]])

In [136]:
mat.shape  # 항상 2차원

(1, 4)

In [138]:
np.asmatrix([1,2,3,4])

matrix([[1, 2, 3, 4]])

In [139]:
m1 = np.matrix([[1,2],[3,4]])
m2 = np.matrix([[1,2],[3,4]])

matrix([[ 7, 10],
        [15, 22]])

In [140]:
m1 * m2  # dot product

matrix([[ 7, 10],
        [15, 22]])

In [142]:
np.multiply(m1,m2)   # element-wise product

matrix([[ 1,  4],
        [ 9, 16]])

In [160]:
dir(np.matrix)[:10]    # 내부 변수 및 메소드 확인

['A',
 'A1',
 'H',
 'I',
 'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__']

In [161]:
m1.T  # or m1.H      Transpose

matrix([[1, 3],
        [2, 4]])

In [162]:
m1.I  # 역행렬

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [163]:
np.linalg.inv(m1)   # 역행렬

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [165]:
m2 = np.mat('1,2,3,4; 5,6,7,8')
m2

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [167]:
m2.I   # 역행렬은 아닌 Pseudo-Inverse

matrix([[-5.50000000e-01,  2.50000000e-01],
        [-2.25000000e-01,  1.25000000e-01],
        [ 1.00000000e-01, -2.08166817e-17],
        [ 4.25000000e-01, -1.25000000e-01]])

In [169]:
try:
    np.linalg.inv(m2)
except Exception as e:
    print(e)

Last 2 dimensions of the array must be square
