In [1]:
import numpy as np

# Contents

* Determinant, 
* Inverse Matrix
* 수반행렬(Adjoint) 

# 행렬식 (Determinant)

In [2]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [4]:
np.linalg.det(x)

-2.0000000000000004

In [6]:
x = np.array([[3,1,3],[2,2,3],[1,1,1]])
x

array([[3, 1, 3],
       [2, 2, 3],
       [1, 1, 1]])

In [7]:
np.linalg.det(x)

-2.0000000000000004

In [9]:
# 수동으로 구해보기 

det11 = np.linalg.det(x[1:, 1:])
det12 = np.linalg.det(x[1:, ::2])
det13 = np.linalg.det(x[1:, :2])
x[0,0]*det11 - x[0,1]*det12 + x[0,2]*det13

-2.0

# 역행렬(Inverse Matrix)

In [10]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [11]:
np.linalg.inv(x)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [16]:
assert np.allclose(np.linalg.inv(x) @ x , np.eye(2)) == True    # A * A_inv = Identity 

In [13]:
 np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 수반행렬(Adjoint) 

* adjA = Cofactors

In [24]:
x = np.arange(1,5).reshape(2,2)
x 

array([[1, 2],
       [3, 4]])

In [30]:
cofactor11 = np.linalg.det(x[1:, 1:])  # 4
cofactor12 = np.linalg.det(x[1:, :1])  # 3
cofactor21 = np.linalg.det(x[:1, 1:])  # 2
cofactor22 = np.linalg.det(x[:1:, :1])  # 1

In [31]:
np.array([cofactor11, cofactor12, cofactor21, cofactor22]).reshape(2,2)

array([[4., 3.],
       [2., 1.]])

# 의사 역행렬 

In [34]:
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
try:
    np.linalg.inv(x)
except Exception as e:
    print(e)

Singular matrix


In [37]:
np.linalg.pinv(x)

array([[0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111]])