In [1]:
import numpy as np

# np.unique 로 유일 원소 식별

In [35]:
x = np.array([7,2,2])
unique, unique_indices, unique_inverse, unique_counts = np.unique(
    x,
    return_index=True,
    return_inverse=True,
    return_counts=True
)

In [36]:
unique

array([2, 7])

In [37]:
unique_indices

array([1, 0])

In [38]:
unique_inverse

array([1, 0, 0])

In [39]:
unique[unique_inverse] # fully recovered

array([7, 2, 2])

In [33]:
unique_counts

array([2, 1])

In [34]:
np.repeat(unique, unique_counts) # recovered but not order preserved

array([2, 2, 7])

# isin으로 포함여부 확인하기

In [43]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [48]:
mask = np.isin(x, [1,3])
mask

array([False,  True, False,  True, False])

In [49]:
x[mask]

array([1, 3])

# 교집합, 합집합, 차집합

In [60]:
x = np.array([[1,2],[3,4]])
y = np.array([[1,22],[3,44]])

In [61]:
np.union1d(x,y)   # Return the unique, sorted array of values that are in either of the two input arrays

array([ 1,  2,  3,  4, 22, 44])

In [62]:
np.intersect1d(x,y) # Return the sorted, unique values that are in both of the input arrays

array([1, 3])

In [63]:
np.setdiff1d(x,y) # X - Y

array([2, 4])

In [64]:
np.setdiff1d(y,x) # Y - X

array([22, 44])

In [66]:
np.setxor1d(x,y)  # Union - Intersect

array([ 2,  4, 22, 44])