In [1]:
import numpy as np

# Contents

* compress로 특징 조건만 추출하기
* squeeze로 차원 없에기
* repeat로 배열 내의 원소 반복하기
* tile로 타일 형상 만들기

## compress로 특징 조건만 추출하기

In [21]:
x = np.array([[1,2],[3,4],[5,6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
np.compress([0,1,0], x)  # flatten 방향으로 mask 전달하여 압축

array([2])

In [26]:
np.compress([0,1,0], x, axis=0) # 행방향으로 mask 전달하여 압축

array([[3, 4]])

In [27]:
np.compress([0,1], x, axis=1) # 열방향으로 mask 전달하여 압축

array([[2],
       [4],
       [6]])

## squeeze로 차원 없에기

In [34]:
x = np.arange(3).reshape(1,3,1)
x

array([[[0],
        [1],
        [2]]])

In [35]:
np.squeeze(x).shape    # 축 지정이 없으면 축차원이 1인 모든 차원을 없엔다.

(3,)

In [37]:
np.squeeze(x, axis=0).shape  # 지정된 축의 차원을 없엔다.

(3, 1)

In [38]:
np.squeeze(x, axis=2).shape  # 지정된 축의 차원을 없엔다.

(1, 3)

## repeat로 배열 내의 원소 반복하기

In [10]:
x = np.arange(1,7).reshape(3,2)
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
np.repeat(x, [2,0,2], axis=0)  # 행방향으로 선택 및 반복 횟수 지정

array([[1, 2],
       [1, 2],
       [5, 6],
       [5, 6]])

In [13]:
np.repeat(x, [1,2], axis=1)  # 열방향으로 선택 및 반복 횟수 지정

array([[1, 2, 2],
       [3, 4, 4],
       [5, 6, 6]])

## tile로 타일 형상 만들기

In [16]:
x = np.arange(0,5).reshape(2,2)
x

array([[1, 2],
       [3, 4]])

In [18]:
np.tile(x, [2,2])

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])