In [1]:
import numpy as np

# contents

* broadcast
* broadcast_to
* broadcast_arrays

# broadcast 수행

In [3]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
y = np.arange(3)
y

array([0, 1, 2])

In [7]:
x + y

array([[0, 2, 4],
       [3, 5, 7]])

# broadcast 함수로 broadcast 흉내내기

In [20]:
z = np.broadcast(x,y)
z

In [21]:
z.shape, z.ndim

((2, 3), 2)

In [22]:
for i in z:     # z 내의 iterator를 조사해서 broadcast된 상황을 이해한다.
    print(i)

(0, 0)
(1, 1)
(2, 2)
(3, 0)
(4, 1)
(5, 2)


In [26]:
z = np.broadcast(x,y)
broadcast_y = np.zeros(z.shape, int)    # 임의 공간 만들기
broadcast_y.flat = [ i for _, i in z ]   # broadcast된 y형상 만들기
broadcast_y

array([[0, 1, 2],
       [0, 1, 2]])

In [27]:
x + broadcast_y

array([[0, 2, 4],
       [3, 5, 7]])

# broadcast_to 로 broadcast 형상 만들기

In [33]:
broadcast_y = np.broadcast_to(y, (2,3))
broadcast_y

array([[0, 1, 2],
       [0, 1, 2]])

In [34]:
x + broadcast_y

array([[0, 2, 4],
       [3, 5, 7]])

# broadcast_arrays 로 동일 형상의 broadcast 준비 형상 만들기 

In [39]:
broadcasted = np.broadcast_arrays(x, y)
broadcasted

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[0, 1, 2],
        [0, 1, 2]])]

In [40]:
broadcasted[0] + broadcasted[1]

array([[0, 2, 4],
       [3, 5, 7]])

# 수작업으로 broadcast 만들어보기 with newaxis

In [46]:
extended = y[np.newaxis,]  # 축 확장 (3, ) => (1,3)
extended.shape

(1, 3)

In [48]:
# vstack으로 broadcast
broadcast_y = np.vstack((extended[0], extended[0]))
broadcast_y

array([[0, 1, 2],
       [0, 1, 2]])

In [49]:
x + broadcast_y

array([[0, 2, 4],
       [3, 5, 7]])

# 열백터와 행백터 브로드케스팅 확장

In [51]:
col_vec = np.arange(1,4).reshape(3,1)   # 열백터
col_vec

array([[1],
       [2],
       [3]])

In [53]:
row_vec = np.arange(1,4).reshape(1,3)
row_vec

array([[1, 2, 3]])

In [54]:
col_vec + row_vec

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [55]:
broadcasted = np.broadcast_arrays(col_vec, row_vec)
broadcasted

[array([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]),
 array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])]

In [56]:
broadcasted[0] + broadcasted[1]

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])