In [1]:
import numpy as np

# 슬라이드 검색

In [2]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
x[0, :]   # 모든 열 선택 

array([0, 1, 2])

In [4]:
x[:, 0]   # 모든 행 선택 

array([0, 3, 6])

In [5]:
x[:2, 1:] # subset 선택 

array([[1, 2],
       [4, 5]])

In [6]:
x.flat[:4]   # 1차원으로 flatten하고 subset

array([0, 1, 2, 3])

In [7]:
x.flat[::2]   # 1차원으로 flatten하고 skip=2로 선택

array([0, 2, 4, 6, 8])

# 생략기호(...)를 사용한 접근

In [8]:
x = np.arange(27).reshape(3,3,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [9]:
type(...)

ellipsis

In [10]:
x[...]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [11]:
x[:2, ...]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [12]:
np.array_equal(x[:2, ...], x[:2, :,:])

True

# 논리식 검색

In [13]:
x = np.array([[1,2],[0,-1]])
x

array([[ 1,  2],
       [ 0, -1]])

In [14]:
x < 0  # 논리를 각 요소별 적용해서 결과 산출 (크기 유지)

array([[False, False],
       [False,  True]])

In [15]:
x[ x < 0 ] # 논리에 충족된 요소 추출 

array([-1])

In [16]:
x.nonzero() # 충족하는 행/열 index를 리턴

(array([0, 0, 1]), array([0, 1, 1]))

In [17]:
x[x.nonzero()] 

array([ 1,  2, -1])

In [18]:
x[ x != 0]  # 동일 표현

array([ 1,  2, -1])

In [19]:
np.logical_and(x,x)   # & 연산 적용

array([[ True,  True],
       [False,  True]])

In [20]:
x[np.logical_not(x)]  # 원소 0만 찾음

array([0])

In [21]:
bool_x = np.arange(0,4).astype(np.bool)
bool_x

array([False,  True,  True,  True])

In [22]:
bool_x | bool_x

array([False,  True,  True,  True])

In [23]:
~ bool_x

array([ True, False, False, False])

# Fancy 검색 

* 인덱스로 검색

## 1D에서의 fancy 검색

In [24]:
x = np.arange(4,10)
x

array([4, 5, 6, 7, 8, 9])

In [25]:
position = np.array([1,2,5,1])
x[position]

array([5, 6, 9, 5])

In [26]:
x[[1,2,5,1]]

array([5, 6, 9, 5])

In [27]:
x[[-1,-2]]

array([9, 8])

## 2D에서의 fancy 검색

* 리스트를 주면 행 검색
* tuple2로 주면 요소 검색 

In [28]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
x[[3,0]]   # 행 검색

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3]])

In [30]:
x[[1,3],[0,3]]    # (1,0) 요소, (3,3) 요소 반환

array([ 4, 15])

In [34]:
# ix_ 를 사용해서 검색

x[ np.ix_([0,2],[0,2])] # 1행,3행, 1열,3열 

array([[ 0,  2],
       [ 8, 10]])

## 다차원 배열로 팬시 검색

In [47]:
x = np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [60]:
x[[0,1],[0,1]]    # (0,0), (1,1) 요소 

array([0, 6])

In [61]:
x[[[0,1],[0,1]],[0,1]]  # (0,0), (1,1) 요소로 만든 2D에서 다시 [0,1] 행선택 

array([[0, 6],
       [0, 6]])

In [62]:
x[0, [0,1]] # 첫번째 행에서 첫째/둘째 열 

array([0, 1])

In [63]:
x[[0,1], 0]  # 첫번째/두번째 행에서 첫번째 열

array([0, 5])

## 팬시 검색과 슬라이스 검색

In [65]:
x = np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [66]:
x[[0,1], -2:]

array([[3, 4],
       [8, 9]])

In [69]:
x[:2, [0,1]]

array([[0, 1],
       [5, 6]])

# 슬라이드 검색은 view, 팬시 검색은 copy

In [70]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [71]:
a = x[1:,1:] # 슬라이드 검색
a

array([[4, 5],
       [7, 8]])

In [73]:
np.may_share_memory(x,a)

True

In [72]:
b = x[1:, [1,2]] # 슬라이드 + 팬시 검색
b

array([[4, 5],
       [7, 8]])

In [74]:
np.may_share_memory(x,b)

False